apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-account.yaml
  - network-policy.yaml
  # API
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml
  # Worker
  - worker/deployment.yaml
  - worker/hpa.yaml
  # Web
  - web/deployment.yaml
  - web/service.yaml
  - web/hpa.yaml
  # PostgreSQL
  - postgres/statefulset.yaml
  - postgres/service.yaml
  # Redis
  - redis/deployment.yaml
  - redis/service.yaml
